//! Unrolled, weight-baked SystemVerilog emitter for one Dense
//! layer. The "ASIC-target" codegen path.
//!
//! ## What it produces
//!
//! Given a `Layer::Dense { in_features, out_features, weights,
//! bias, requant, x_zp, w_zp, out_zp }`, writes:
//!
//! - `top.sv` — module `top` with the same external interface as
//!   `rlx-fpga::codegen`'s emit (`clk`, `rst`, `start`, `done`,
//!   `in_addr`, `in_we`, `in_din`, `pred`) so the bench's
//!   `RtlSimBackend` testbench protocol just works. Inside:
//!   - `IN_BUF` register array (`in_features` × i8) loaded by the
//!     standard BRAM-write protocol.
//!   - `localparam logic signed [7:0] W [0:OUT-1][0:IN-1]` —
//!     **every weight as a constant**, baked into the gate-level
//!     netlist when synthesized.
//!   - `localparam` arrays for bias + per-channel `(M0, shift,
//!     out_zp)` requant.
//!   - Combinational MAC: every (oc, ic) multiply-accumulate runs
//!     in parallel, no serializing controller. Output ready in 1
//!     cycle after `start`.
//!   - Combinational argmax across the 10 output logits.
//! - `tb_unrolled.sv` — testbench reading `tb_image.mem` and
//!   feeding it through the same protocol. Includes the cycle
//!   counter `RtlSimBackend` parses.
//!
//! ## Cycle count
//!
//! With the BRAM-write input phase preserved (one byte per cycle),
//! total = `in_features` (write) + ~3 (start handshake + compute +
//! done) ≈ `in_features + 3` cycles per inference. For Dense(400 →
//! 10) that's ~403 cycles, vs ~4 000 for the sequential FPGA emit
//! of the same layer.
//!
//! Future: parallel input loading (one wire per byte) drops the
//! cycle count to ~3.
//!
//! ## What's NOT here yet
//!
//! - Pipeline registers between MAC and requant — for v1 the whole
//!   compute is combinational. Real synthesis may force pipelining
//!   to meet timing; that's a v1.5 follow-up.
//! - Conv2d / ReLU / MaxPool / Argmax-as-separate-layer support.
//!   v1 demonstrates the principle on Dense; the same pattern
//!   scales to all layer types.

use std::fmt::Write;
use std::path::Path;

use rlx_fpga::model::Layer;

#[derive(Debug, thiserror::Error)]
pub enum EmitError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("emit: layer is not Dense — only Dense is supported in v1")]
    NotDense,
    #[error("emit: layer dimensions don't match weight blob: \
             expected {expected} weights, got {actual}")]
    WeightDimMismatch { expected: usize, actual: usize },
    #[error("emit: weight_bits {0} not supported (v1 = 8 only)")]
    UnsupportedWeightBits(u8),
}

/// Emit the `top.sv` file for an unrolled Dense layer. Returns the
/// number of `localparam` weight bytes embedded (a sanity number
/// for the Report's bundle section).
pub fn emit_unrolled_dense_top(layer: &Layer, output_path: &Path) -> Result<usize, EmitError> {
    let (in_features, out_features, weights, bias, requant, x_zp, w_zp, out_zp, weight_bits) =
        match layer {
            Layer::Dense {
                in_features,
                out_features,
                weights,
                bias,
                requant,
                x_zp,
                w_zp,
                out_zp,
                weight_bits,
                ..
            } => (
                *in_features,
                *out_features,
                weights.clone(),
                bias.clone(),
                requant.clone(),
                *x_zp,
                *w_zp,
                *out_zp,
                *weight_bits,
            ),
            _ => return Err(EmitError::NotDense),
        };

    if weight_bits != 8 {
        return Err(EmitError::UnsupportedWeightBits(weight_bits));
    }
    let expected = in_features * out_features;
    if weights.len() != expected {
        return Err(EmitError::WeightDimMismatch {
            expected,
            actual: weights.len(),
        });
    }

    let mut s = String::new();
    let _ = writeln!(s, "// Auto-generated by spike-tinyconv-array::codegen::unrolled");
    let _ = writeln!(s, "// Strategy: BakedConstants — every weight is a localparam.");
    let _ = writeln!(s, "// in_features = {in_features}, out_features = {out_features}");
    let _ = writeln!(s, "`timescale 1ns/1ps");
    let _ = writeln!(s);

    // ── Top module ────────────────────────────────────────────
    let _ = writeln!(s, "module top (");
    let _ = writeln!(s, "    input  logic                       clk,");
    let _ = writeln!(s, "    input  logic                       rst,");
    let _ = writeln!(s, "    input  logic                       start,");
    let _ = writeln!(s, "    output logic                       done,");
    let in_addr_bits = bits_for(in_features);
    let _ = writeln!(s, "    input  logic [{}:0]              in_addr,", in_addr_bits - 1);
    let _ = writeln!(s, "    input  logic                       in_we,");
    let _ = writeln!(s, "    input  logic signed [7:0]          in_din,");
    let _ = writeln!(s, "    output logic signed [7:0]          pred");
    let _ = writeln!(s, ");");

    // ── Input register file (BRAM-shaped for protocol compat) ─
    let _ = writeln!(
        s,
        "    logic signed [7:0] in_buf [0:{}];",
        in_features - 1
    );
    let _ = writeln!(s, "    always_ff @(posedge clk) begin");
    let _ = writeln!(s, "        if (in_we) in_buf[in_addr] <= in_din;");
    let _ = writeln!(s, "    end");
    let _ = writeln!(s);

    // ── Weight constants ─────────────────────────────────────
    // Stored as a single packed bit vector to keep the SV inside what
    // Yosys's parser accepts (multi-dim unpacked-array localparam
    // initializers are not supported). Slice with `+:` at use-time.
    let _ = writeln!(s, "    // Weights baked as constants — synthesizer hard-wires these");
    let _ = writeln!(s, "    // into the gate-level netlist. No BRAM. No fetch cycles.");
    let _ = writeln!(s, "    localparam int IN  = {in_features};");
    let _ = writeln!(s, "    localparam int OUT = {out_features};");
    let bias_vec: Vec<i32> = bias.unwrap_or_else(|| vec![0; out_features]);

    // W_FLAT: little-end (`(oc*IN+ic)*8 +: 8`) holds W[oc][ic].
    let _ = writeln!(s, "    localparam logic [{}:0] W_FLAT = {{", out_features * in_features * 8 - 1);
    emit_packed_concat_8(&mut s, out_features, in_features, &weights);
    let _ = writeln!(s, "    }};");

    // B_FLAT: 32-bit per output channel.
    let _ = writeln!(s, "    localparam logic [{}:0] B_FLAT = {{", out_features * 32 - 1);
    emit_packed_concat_32(&mut s, &bias_vec);
    let _ = writeln!(s, "    }};");

    // M0_FLAT: 32-bit per output channel.
    let m0_vec: Vec<i32> = requant.iter().map(|r| r.0).collect();
    let _ = writeln!(s, "    localparam logic [{}:0] M0_FLAT = {{", out_features * 32 - 1);
    emit_packed_concat_32(&mut s, &m0_vec);
    let _ = writeln!(s, "    }};");

    // SHIFT_FLAT: 8-bit per output channel (shifts are small).
    let shift_vec: Vec<i32> = requant.iter().map(|r| r.1 as i32).collect();
    let _ = writeln!(s, "    localparam logic [{}:0] SHIFT_FLAT = {{", out_features * 8 - 1);
    emit_packed_concat_shift8(&mut s, &shift_vec);
    let _ = writeln!(s, "    }};");

    let _ = writeln!(s, "    localparam int X_ZP   = {x_zp};");
    let _ = writeln!(s, "    localparam int W_ZP   = {w_zp};");
    let _ = writeln!(s, "    localparam int OUT_ZP = {out_zp};");
    let _ = writeln!(s);

    // ── Combinational MAC + requant + argmax ─────────────────
    let _ = writeln!(s, "    // Per-channel accumulator: every (oc, ic) MAC runs in parallel.");
    let _ = writeln!(s, "    // Synthesis materializes OUT × IN dedicated multipliers.");
    let _ = writeln!(s, "    logic signed [31:0] acc [0:OUT-1];");
    let _ = writeln!(s, "    logic signed [7:0]  y   [0:OUT-1];");
    let _ = writeln!(s);
    let _ = writeln!(s, "    always_comb begin");
    let _ = writeln!(s, "        for (int oc = 0; oc < OUT; oc++) begin");
    let _ = writeln!(s, "            automatic logic signed [31:0] b_oc;");
    let _ = writeln!(s, "            automatic logic signed [31:0] m0_oc;");
    let _ = writeln!(s, "            automatic logic signed [7:0]  w_oc_ic;");
    let _ = writeln!(s, "            b_oc  = $signed(B_FLAT[oc*32 +: 32]);");
    let _ = writeln!(s, "            m0_oc = $signed(M0_FLAT[oc*32 +: 32]);");
    let _ = writeln!(s, "            acc[oc] = b_oc;");
    let _ = writeln!(s, "            for (int ic = 0; ic < IN; ic++) begin");
    let _ = writeln!(s, "                w_oc_ic = $signed(W_FLAT[(oc*IN + ic)*8 +: 8]);");
    let _ = writeln!(s, "                acc[oc] += ((32'(in_buf[ic]) - X_ZP) *");
    let _ = writeln!(s, "                            (32'(w_oc_ic)    - W_ZP));");
    let _ = writeln!(s, "            end");
    let _ = writeln!(s, "            // Q0.31 requantize (srdhm + rdpot + zp)");
    let _ = writeln!(s, "            begin");
    let _ = writeln!(s, "                automatic logic signed [63:0] mul64;");
    let _ = writeln!(s, "                automatic logic signed [31:0] srdhm_out;");
    let _ = writeln!(s, "                automatic logic signed [31:0] shifted;");
    let _ = writeln!(s, "                automatic logic signed [31:0] zpd;");
    let _ = writeln!(s, "                automatic int unsigned shamt;");
    let _ = writeln!(s, "                mul64 = $signed({{32'd0, m0_oc}}) * $signed({{32'd0, acc[oc]}});");
    let _ = writeln!(s, "                mul64 = mul64 + 64'sd1073741824; // round add 2^30");
    let _ = writeln!(s, "                srdhm_out = mul64 >>> 31;");
    let _ = writeln!(s, "                shamt = SHIFT_FLAT[oc*8 +: 8];");
    let _ = writeln!(s, "                shifted = srdhm_out >>> shamt;");
    let _ = writeln!(s, "                zpd = shifted + OUT_ZP;");
    let _ = writeln!(s, "                if (zpd > 127)        y[oc] = 8'sd127;");
    let _ = writeln!(s, "                else if (zpd < -128)  y[oc] = -8'sd128;");
    let _ = writeln!(s, "                else                  y[oc] = zpd[7:0];");
    let _ = writeln!(s, "            end");
    let _ = writeln!(s, "        end");
    let _ = writeln!(s, "    end");
    let _ = writeln!(s);

    // ── Argmax (combinational) ─────────────────────────────
    let _ = writeln!(s, "    // Combinational argmax across {out_features} logits.");
    let _ = writeln!(s, "    logic signed [7:0] best_v;");
    let _ = writeln!(s, "    logic [7:0]        best_i;");
    let _ = writeln!(s, "    always_comb begin");
    let _ = writeln!(s, "        best_v = -8'sd128;");
    let _ = writeln!(s, "        best_i = 8'd0;");
    let _ = writeln!(s, "        for (int i = 0; i < OUT; i++) begin");
    let _ = writeln!(s, "            if (y[i] > best_v) begin");
    let _ = writeln!(s, "                best_v = y[i];");
    let _ = writeln!(s, "                best_i = i[7:0];");
    let _ = writeln!(s, "            end");
    let _ = writeln!(s, "        end");
    let _ = writeln!(s, "    end");
    let _ = writeln!(s);

    // ── Output handshake ───────────────────────────────────
    let _ = writeln!(s, "    // One-cycle done after start: compute is combinational, so");
    let _ = writeln!(s, "    // a single register stage produces `done` deterministically.");
    let _ = writeln!(s, "    logic done_q;");
    let _ = writeln!(s, "    logic signed [7:0] pred_q;");
    let _ = writeln!(s, "    always_ff @(posedge clk) begin");
    let _ = writeln!(s, "        if (rst) begin");
    let _ = writeln!(s, "            done_q <= 1'b0;");
    let _ = writeln!(s, "            pred_q <= 8'sd0;");
    let _ = writeln!(s, "        end else if (start) begin");
    let _ = writeln!(s, "            done_q <= 1'b1;");
    let _ = writeln!(s, "            pred_q <= $signed(best_i);");
    let _ = writeln!(s, "        end else begin");
    let _ = writeln!(s, "            done_q <= 1'b0;");
    let _ = writeln!(s, "        end");
    let _ = writeln!(s, "    end");
    let _ = writeln!(s, "    assign done = done_q;");
    let _ = writeln!(s, "    assign pred = pred_q;");
    let _ = writeln!(s, "endmodule");

    if let Some(parent) = output_path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }
    std::fs::write(output_path, &s)?;
    Ok(weights.len())
}

/// Emit the testbench module. Same protocol as
/// `RtlSimBackend::generate_testbench` so the existing parser
/// understands the output: `RESULT pred=N cycles=N`.
pub fn emit_unrolled_dense_tb(
    in_features: usize,
    output_path: &Path,
) -> Result<(), EmitError> {
    let in_addr_bits = bits_for(in_features);
    let s = format!(
        r#"// Auto-generated testbench for unrolled Dense top.
`timescale 1ns/1ps
module tb_bench;
    logic clk = 0;
    always #5 clk = ~clk;
    logic rst = 1;
    logic start = 0;
    logic done;
    logic [{addr_max}:0] in_addr = '0;
    logic in_we = 0;
    logic signed [7:0] in_din = '0;
    logic signed [7:0] pred;

    top u_top (
        .clk(clk), .rst(rst), .start(start), .done(done),
        .in_addr(in_addr), .in_we(in_we), .in_din(in_din),
        .pred(pred)
    );

    logic signed [7:0] image_mem [0:{n_minus_1}];

    longint cycles_counter = 0;
    logic counting = 0;
    always @(posedge clk) begin
        if (counting && !done) cycles_counter <= cycles_counter + 1;
        if (start) counting <= 1;
        if (done) counting <= 0;
    end

    initial begin
        $readmemh("tb_image.mem", image_mem);
        rst = 1; #20; rst = 0;
        for (int i = 0; i < {n}; i++) begin
            @(posedge clk);
            in_addr <= i[{addr_max}:0];
            in_we <= 1'b1;
            in_din <= image_mem[i];
        end
        @(posedge clk); in_we <= 1'b0;
        @(posedge clk); start <= 1'b1;
        wait (done);
        @(posedge clk); start <= 1'b0;
        $display("RESULT pred=%0d cycles=%0d", $signed(pred), cycles_counter);
        $finish;
    end
endmodule
"#,
        n = in_features,
        n_minus_1 = in_features - 1,
        addr_max = in_addr_bits - 1,
    );
    if let Some(parent) = output_path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }
    std::fs::write(output_path, s)?;
    Ok(())
}

/// Emit one self-contained SV file per output channel — `dense_oc_<n>.sv`,
/// each module computing one logit `y[n]` from `in_buf`. Returns the
/// list of paths emitted.
///
/// Why: monolithic-top synthesis through `abc -fast` is bottlenecked
/// by single-thread structural hashing. Per-channel modules can be
/// synthesized in parallel — `OUT` independent ABC processes — and
/// areas summed for the same total. ~OUT× wall-time speedup.
pub fn emit_unrolled_dense_per_channel(
    layer: &Layer,
    out_dir: &std::path::Path,
) -> Result<Vec<std::path::PathBuf>, EmitError> {
    let (in_features, out_features, weights, bias, requant, x_zp, w_zp, out_zp, weight_bits) =
        match layer {
            Layer::Dense {
                in_features,
                out_features,
                weights,
                bias,
                requant,
                x_zp,
                w_zp,
                out_zp,
                weight_bits,
                ..
            } => (
                *in_features,
                *out_features,
                weights.clone(),
                bias.clone(),
                requant.clone(),
                *x_zp,
                *w_zp,
                *out_zp,
                *weight_bits,
            ),
            _ => return Err(EmitError::NotDense),
        };
    if weight_bits != 8 {
        return Err(EmitError::UnsupportedWeightBits(weight_bits));
    }
    let bias_vec: Vec<i32> = bias.unwrap_or_else(|| vec![0; out_features]);
    std::fs::create_dir_all(out_dir)?;

    let mut paths = Vec::with_capacity(out_features);
    for oc in 0..out_features {
        let mut s = String::new();
        let _ = writeln!(s, "// Auto-generated per-channel module dense_oc_{oc}");
        let _ = writeln!(s, "`timescale 1ns/1ps");
        let _ = writeln!(s, "module dense_oc_{oc} (");
        let _ = writeln!(s, "    input  logic [{}:0] in_buf_flat,", in_features * 8 - 1);
        let _ = writeln!(s, "    output logic signed [7:0] y_oc");
        let _ = writeln!(s, ");");
        let _ = writeln!(s, "    localparam int IN = {in_features};");

        // Per-channel weights.
        let _ = writeln!(s, "    localparam logic [{}:0] W_FLAT = {{", in_features * 8 - 1);
        let mut first = true;
        for ic in (0..in_features).rev() {
            if !first { s.push(','); }
            if ic % 16 == 0 { s.push_str("\n        "); } else { s.push(' '); }
            let w = weights[oc * in_features + ic];
            let _ = std::fmt::Write::write_fmt(&mut s, format_args!("8'h{:02x}", w as u8));
            first = false;
        }
        let _ = writeln!(s, "\n    }};");

        // Bias / M0 / shift constants for this channel only.
        let _ = writeln!(s, "    localparam logic signed [31:0] B  = 32'h{:08x};", bias_vec[oc] as u32);
        let _ = writeln!(s, "    localparam logic signed [31:0] M0 = 32'h{:08x};", requant[oc].0 as u32);
        let _ = writeln!(s, "    localparam int SHAMT = {};", requant[oc].1);
        let _ = writeln!(s, "    localparam int X_ZP = {x_zp};");
        let _ = writeln!(s, "    localparam int W_ZP = {w_zp};");
        let _ = writeln!(s, "    localparam int OUT_ZP = {out_zp};");

        // MAC + Q0.31 requant.
        let _ = writeln!(s, "    always_comb begin");
        let _ = writeln!(s, "        automatic logic signed [31:0] acc;");
        let _ = writeln!(s, "        automatic logic signed [7:0]  w_ic;");
        let _ = writeln!(s, "        automatic logic signed [63:0] mul64;");
        let _ = writeln!(s, "        automatic logic signed [31:0] srdhm_out;");
        let _ = writeln!(s, "        automatic logic signed [31:0] shifted;");
        let _ = writeln!(s, "        automatic logic signed [31:0] zpd;");
        let _ = writeln!(s, "        automatic logic signed [7:0] x_ic;");
        let _ = writeln!(s, "        acc = B;");
        let _ = writeln!(s, "        for (int ic = 0; ic < IN; ic++) begin");
        let _ = writeln!(s, "            w_ic = $signed(W_FLAT[ic*8 +: 8]);");
        let _ = writeln!(s, "            x_ic = $signed(in_buf_flat[ic*8 +: 8]);");
        let _ = writeln!(s, "            acc += ((32'(x_ic) - X_ZP) * (32'(w_ic) - W_ZP));");
        let _ = writeln!(s, "        end");
        let _ = writeln!(s, "        mul64 = $signed({{32'd0, M0}}) * $signed({{32'd0, acc}});");
        let _ = writeln!(s, "        mul64 = mul64 + 64'sd1073741824;");
        let _ = writeln!(s, "        srdhm_out = mul64 >>> 31;");
        let _ = writeln!(s, "        shifted   = srdhm_out >>> SHAMT;");
        let _ = writeln!(s, "        zpd       = shifted + OUT_ZP;");
        let _ = writeln!(s, "        if (zpd > 127)        y_oc = 8'sd127;");
        let _ = writeln!(s, "        else if (zpd < -128)  y_oc = -8'sd128;");
        let _ = writeln!(s, "        else                  y_oc = zpd[7:0];");
        let _ = writeln!(s, "    end");
        let _ = writeln!(s, "endmodule");

        let path = out_dir.join(format!("dense_oc_{oc}.sv"));
        std::fs::write(&path, s)?;
        paths.push(path);
    }
    Ok(paths)
}

/// Emit a packed-bit-vector concatenation for the weight matrix.
/// MSB → LSB ordering matches `+:` slicing: index `(oc*IN+ic)*8 +: 8`
/// recovers `weights[oc*IN + ic]`. Verilog concatenations are
/// MSB-first, so we emit from the highest index down.
fn emit_packed_concat_8(s: &mut String, out_features: usize, in_features: usize, weights: &[i8]) {
    let total = out_features * in_features;
    let mut first = true;
    for k in (0..total).rev() {
        if !first {
            s.push_str(",");
        }
        if k % 16 == 0 {
            s.push_str("\n        ");
        } else {
            s.push(' ');
        }
        let w = weights[k];
        // Use raw 2's-complement byte to skip the signed/unsigned dance.
        let _ = std::fmt::Write::write_fmt(s, format_args!("8'h{:02x}", w as u8));
        first = false;
    }
    s.push('\n');
}

fn emit_packed_concat_32(s: &mut String, vals: &[i32]) {
    let mut first = true;
    for k in (0..vals.len()).rev() {
        if !first {
            s.push_str(",");
        }
        if k % 4 == 0 {
            s.push_str("\n        ");
        } else {
            s.push(' ');
        }
        let v = vals[k] as u32;
        let _ = std::fmt::Write::write_fmt(s, format_args!("32'h{:08x}", v));
        first = false;
    }
    s.push('\n');
}

fn emit_packed_concat_shift8(s: &mut String, vals: &[i32]) {
    let mut first = true;
    for k in (0..vals.len()).rev() {
        if !first {
            s.push_str(",");
        }
        s.push(' ');
        let v = (vals[k] & 0xff) as u8;
        let _ = std::fmt::Write::write_fmt(s, format_args!("8'h{:02x}", v));
        first = false;
    }
    s.push('\n');
}

fn bits_for(n: usize) -> usize {
    let mut b = 1;
    while (1usize << b) < n {
        b += 1;
    }
    b
}
